import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
export default function Home() {
  return (
    <>
      <Head>
        <title>index</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.flex_conent}>
          <Image src={"/images/image.jpg"} width={387} height={252} alt="" />
          <h4 className={styles.flex}>
            Finally-a natural extension of your self.
          </h4>
        </div>
      </main>
    </>
  );
}
